import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Octokit } from '@octokit/rest';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

interface FileToCommit {
  path: string;
  content: string;
}

interface DeploymentResult {
  url: string;
  projectId: string;
}

@Injectable()
export class CodespacesService {
  private readonly logger = new Logger(CodespacesService.name);
  private octokit: Octokit | null = null;
  private githubToken: string;
  private githubUsername: string;
  private vercelToken: string;

  constructor(private configService: ConfigService) {
    this.githubToken =
      this.configService.get<string>('github.token') || '';
    this.githubUsername =
      this.configService.get<string>('github.username') || '';
    this.vercelToken =
      this.configService.get<string>('vercel.token') || '';

    if (this.githubToken) {
      this.octokit = new Octokit({ auth: this.githubToken });
      this.logger.log('CodespacesService initialized with GitHub token');
    } else {
      this.logger.warn('GITHUB_TOKEN not set — CodespacesService disabled');
    }
  }

  async executeInCodespace(
    command: string,
    timeout = 120000,
  ): Promise<string> {
    const codespaceName =
      this.configService.get<string>('github.codespaceName') || '';

    if (!codespaceName) {
      throw new Error('Codespace name not configured');
    }

    try {
      const { stdout, stderr } = await execAsync(
        `gh codespace ssh -c ${codespaceName} -- "${command.replace(/"/g, '\\"')}"`,
        {
          timeout,
          env: { ...process.env, GITHUB_TOKEN: this.githubToken },
        },
      );

      if (stderr) {
        this.logger.warn(`Codespace stderr: ${stderr.substring(0, 500)}`);
      }

      return stdout;
    } catch (error) {
      this.logger.error(
        'Codespace command execution failed',
        (error as Error).message,
      );
      throw error;
    }
  }

  async createRepository(name: string): Promise<{ owner: string; repo: string; url: string }> {
    if (!this.octokit) {
      throw new Error('GitHub client not initialized');
    }

    try {
      const response = await this.octokit.repos.createForAuthenticatedUser({
        name,
        auto_init: true,
        private: false,
        description: `Generated by Synapse AI Coder`,
      });

      this.logger.log(`Repository created: ${response.data.full_name}`);

      return {
        owner: response.data.owner.login,
        repo: response.data.name,
        url: response.data.html_url,
      };
    } catch (error) {
      this.logger.error(
        'Failed to create repository',
        (error as Error).message,
      );
      throw error;
    }
  }

  async pushFiles(
    owner: string,
    repo: string,
    files: FileToCommit[],
  ): Promise<void> {
    if (!this.octokit) {
      throw new Error('GitHub client not initialized');
    }

    try {
      const refResponse = await this.octokit.git.getRef({
        owner,
        repo,
        ref: 'heads/main',
      });
      const latestCommitSha = refResponse.data.object.sha;

      const commitResponse = await this.octokit.git.getCommit({
        owner,
        repo,
        commit_sha: latestCommitSha,
      });
      const baseTreeSha = commitResponse.data.tree.sha;

      const treeItems = await Promise.all(
        files.map(async (file) => {
          const blobResponse = await this.octokit!.git.createBlob({
            owner,
            repo,
            content: Buffer.from(file.content).toString('base64'),
            encoding: 'base64',
          });
          return {
            path: file.path,
            mode: '100644' as const,
            type: 'blob' as const,
            sha: blobResponse.data.sha,
          };
        }),
      );

      const treeResponse = await this.octokit.git.createTree({
        owner,
        repo,
        base_tree: baseTreeSha,
        tree: treeItems,
      });

      const newCommitResponse = await this.octokit.git.createCommit({
        owner,
        repo,
        message: 'Generated by Synapse AI Coder',
        tree: treeResponse.data.sha,
        parents: [latestCommitSha],
      });

      await this.octokit.git.updateRef({
        owner,
        repo,
        ref: 'heads/main',
        sha: newCommitResponse.data.sha,
      });

      this.logger.log(
        `Pushed ${files.length} files to ${owner}/${repo}`,
      );
    } catch (error) {
      this.logger.error(
        'Failed to push files to repository',
        (error as Error).message,
      );
      throw error;
    }
  }

  async deployToVercel(
    projectName: string,
    repoFullName: string,
  ): Promise<DeploymentResult> {
    if (!this.vercelToken) {
      throw new Error('Vercel token not configured');
    }

    try {
      const createProjectResponse = await fetch(
        'https://api.vercel.com/v10/projects',
        {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${this.vercelToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            name: projectName,
            framework: null,
            gitRepository: {
              repo: repoFullName,
              type: 'github',
            },
          }),
        },
      );

      if (!createProjectResponse.ok) {
        const errorBody = await createProjectResponse.text();
        throw new Error(
          `Vercel project creation failed: ${createProjectResponse.status} — ${errorBody}`,
        );
      }

      const projectData = (await createProjectResponse.json()) as {
        id: string;
        name: string;
      };

      const deployResponse = await fetch(
        'https://api.vercel.com/v13/deployments',
        {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${this.vercelToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            name: projectName,
            project: projectData.id,
            gitSource: {
              type: 'github',
              repo: repoFullName,
              ref: 'main',
            },
          }),
        },
      );

      if (!deployResponse.ok) {
        const errorBody = await deployResponse.text();
        throw new Error(
          `Vercel deployment failed: ${deployResponse.status} — ${errorBody}`,
        );
      }

      const deployData = (await deployResponse.json()) as {
        id: string;
        url: string;
      };

      this.logger.log(
        `Deployed to Vercel: https://${deployData.url}`,
      );

      return {
        url: `https://${deployData.url}`,
        projectId: projectData.id,
      };
    } catch (error) {
      this.logger.error(
        'Failed to deploy to Vercel',
        (error as Error).message,
      );
      throw error;
    }
  }
}
